### ISSUE TITLE
如何自学的图片为空白内容

### ISSUE THREAD

**Issue by CsongL** [KieSun/all-of-frontend#96]
不知道是不是只是我这边显示的问题，如何自学的学习方法的图片是一张空白的图片
麻烦您看一下是什么问题
![image](https://user-images.githubusercontent.com/30070610/137409002-1d8d1a0c-683b-442e-b127-082e0f3bfd21.png)

**Comment by codersjj** [comment]
![image](https://user-images.githubusercontent.com/44868357/137432496-bfe32524-03f0-4952-b026-56af318d0672.png)

**Comment by CsongL** [comment]
Thanks♪(･ω･)ﾉ
